# Generated by Django 3.1.7 on 2021-08-09 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('PostId', models.AutoField(primary_key=True, serialize=False)),
                ('Content', models.FileField(upload_to='Posts/')),
                ('Caption', models.CharField(max_length=1024, null=True)),
                ('Event', models.CharField(max_length=254)),
                ('Time', models.DateTimeField()),
                ('Poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LikedPostId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Posts.posts')),
                ('LikerPid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.CharField(max_length=1024)),
                ('Time', models.DateTimeField()),
                ('LikedPostId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Posts.posts')),
                ('LikerPid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
