# Generated by Django 3.1.7 on 2021-08-09 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=254)),
                ('Subject', models.CharField(max_length=254)),
                ('Message', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.IntegerField(null=True)),
                ('Status', models.CharField(max_length=1024)),
                ('Address', models.CharField(max_length=1024)),
                ('Phone', models.CharField(max_length=254)),
                ('ProfilePicture', models.ImageField(default='ProfilePictures/DefaultDP.jpg', max_length=1024, null=True, upload_to='ProfilePictures/')),
                ('Profession', models.CharField(max_length=254)),
                ('ThisUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
