# Generated by Django 3.1.7 on 2021-08-09 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.BooleanField(default=True)),
                ('Age', models.BooleanField(default=True)),
                ('Address', models.BooleanField(default=True)),
                ('Phone', models.BooleanField(default=True)),
                ('Profession', models.BooleanField(default=True)),
                ('Educations', models.BooleanField(default=True)),
                ('Hobbies', models.BooleanField(default=True)),
                ('ThisUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
